-- Seed konten awal LSP FIT. Data konten lama sengaja diganti dengan data ini.
DELETE FROM kegiatan;
DELETE FROM anggota;
DELETE FROM partners;

INSERT INTO anggota (name, role_label, photo_url, sort_order) VALUES
  ('Eva Rosmalia', 'Dewan Komisaris', '/assets/asesor/dewanpengarah.jpeg', 7),
  ('Bambang Satrio Lelono', 'Dewan Komisaris', '/assets/asesor/dewanpengarah.jpeg', 6),
  ('Fitri Firmansyah', 'Direktur', '/assets/asesor/direktur.jpeg', 5),
  ('Arum Handayani', 'Bidang Mutu', '/assets/asesor/bagianmutu.jpeg', 4),
  ('Rahayu Wibowo', 'Bidang Sertifikasi', '/assets/asesor/rahayu wibowo.png', 3),
  ('M. Reza Aditya', 'Finance', 'https://ui-avatars.com/api/?name=M.+Reza+Aditya&size=600&background=E6F4FB&color=0D1B2A', 2),
  ('Annisa Ramadaniah', 'Bidang Administrasi', 'https://ui-avatars.com/api/?name=Annisa+Ramadaniah&size=600&background=E6F4FB&color=0D1B2A', 1);

INSERT INTO partners (name, logo_url, website_url, sort_order) VALUES
  ('UDN', '/assets/partners/udn.jpeg', NULL, 22), ('STIA LAN', '/assets/partners/stialan.jpeg', NULL, 21),
  ('SLS', '/assets/partners/sls.jpeg', NULL, 20), ('PALYJA', '/assets/partners/palyja.jpeg', NULL, 19),
  ('Sanggar', '/assets/partners/sanggar.jpeg', NULL, 18), ('Madhani', '/assets/partners/madhani.jpeg', NULL, 17),
  ('Sampoerna', '/assets/partners/sampoerna.jpeg', NULL, 16), ('Kesehatan', '/assets/partners/kesehatan.jpg', NULL, 15),
  ('Kemnaker', '/assets/partners/kemnaker.jpeg', NULL, 14), ('RAPP', '/assets/partners/rapp.jpeg', NULL, 13),
  ('ITI', '/assets/partners/iti.jpeg', NULL, 12), ('Infomedia', '/assets/partners/infomedia.jpeg', NULL, 11),
  ('Citibank', '/assets/partners/citibank.jpeg', NULL, 10), ('Borneo', '/assets/partners/borneo.jpeg', NULL, 9),
  ('Bogor', '/assets/partners/bogor.jpeg', NULL, 8), ('Berau', '/assets/partners/berau.jpeg', NULL, 7),
  ('AHM', '/assets/partners/ahm.jpeg', NULL, 6), ('Perikanan', '/assets/partners/perikanan.jpeg', NULL, 5),
  ('Perhubungan', '/assets/partners/perhubungan.jpeg', NULL, 4), ('Petrosea', '/assets/partners/petrosea.jpeg', NULL, 3),
  ('PUPR', '/assets/partners/pupr.jpeg', NULL, 2);

INSERT INTO kegiatan (title, slug, category, summary, description, image_url, is_highlight, sort_order) VALUES
  ('Pelaksanaan Program Pembelajaran', 'pelaksanaan-program-pembelajaran', 'Bidang Instruktur - Klaster', 'Kompetensi untuk melaksanakan program pembelajaran secara terstruktur dan efektif.', 'Kompetensi untuk melaksanakan program pembelajaran secara terstruktur, efektif, dan sesuai kebutuhan peserta.', '/assets/lspfit/logofit-nobg.png', 1, 11),
  ('Penyajian Materi Pembelajaran Daring', 'penyajian-materi-pembelajaran-daring', 'Bidang Instruktur - Klaster', 'Kompetensi untuk menyajikan materi pembelajaran melalui metode dan platform daring.', 'Kompetensi untuk menyajikan materi pembelajaran melalui metode dan platform pembelajaran daring.', '/assets/lspfit/logofit-nobg.png', 1, 10),
  ('Perencanaan Penyajian Materi Pelatihan', 'perencanaan-penyajian-materi-pelatihan', 'Bidang Instruktur - Klaster', 'Kompetensi untuk merancang materi, metode, dan media pelatihan.', 'Kompetensi untuk merancang alur, materi, metode, dan media pelatihan yang relevan.', '/assets/lspfit/logofit-nobg.png', 1, 9),
  ('Asisten hingga Instruktur Terampil', 'asisten-hingga-instruktur-terampil', 'Bidang Instruktur - Jenjang 3', 'Skema bagi asisten, mentor, pelatih, dan instruktur terampil.', 'Asisten Instruktur, Mentor, Pelatih, Pelatih di Tempat Kerja, Instruktur Junior, dan Instruktur Terampil.', '/assets/lspfit/logofit-nobg.png', 0, 8),
  ('Instruktur dan Fasilitator', 'instruktur-dan-fasilitator', 'Bidang Instruktur - Jenjang 4', 'Skema bagi instruktur, fasilitator, dan pengajar vokasi.', 'Instruktur Pertama, Instruktur, Fasilitator, Pengajar Vokasi, dan Instruktur Penyelia.', '/assets/lspfit/logofit-nobg.png', 0, 7),
  ('Instruktur Muda dan Senior', 'instruktur-muda-dan-senior', 'Bidang Instruktur - Jenjang 5', 'Skema untuk instruktur dengan pengalaman pengembangan pembelajaran.', 'Instruktur Muda dan Instruktur Senior.', '/assets/lspfit/logofit-nobg.png', 0, 6),
  ('Instruktur Madya dan Master', 'instruktur-madya-dan-master', 'Bidang Instruktur - Jenjang 6', 'Skema tingkat lanjut untuk pengembangan dan mutu pembelajaran.', 'Instruktur Madya dan Instruktur Master.', '/assets/lspfit/logofit-nobg.png', 0, 5),
  ('Operasional Pelatihan', 'operasional-pelatihan', 'Bidang Tenaga Kepelatihan - Jenjang 3', 'Skema untuk operasional, administrasi, dan penyelenggaraan pelatihan.', 'Staf Administrasi, Pelaksanaan Kegiatan Pelatihan, Pelatihan Pemasar Program, Pengelola Rekrutmen dan Seleksi, Penyelenggara Pelatihan, Penyedia Bahan Pelatihan, dan Penata Diklat.', '/assets/lspfit/logofit-nobg.png', 0, 4),
  ('Koordinator dan Pengembang', 'koordinator-dan-pengembang', 'Bidang Tenaga Kepelatihan - Jenjang 4', 'Skema untuk koordinasi dan pengembangan lembaga pelatihan.', 'Koordinator Pemagangan serta Pengembang Kurikulum dan Fasilitas Pelatihan.', '/assets/lspfit/logofit-nobg.png', 0, 3),
  ('Manager', 'manager-pelatihan', 'Bidang Tenaga Kepelatihan - Jenjang 5', 'Kompetensi untuk mengelola fungsi manajerial pelatihan.', 'Manager.', '/assets/lspfit/logofit-nobg.png', 0, 2),
  ('Kepala Lembaga Pelatihan', 'kepala-lembaga-pelatihan', 'Bidang Tenaga Kepelatihan - Jenjang 6', 'Kompetensi tingkat lanjut untuk memimpin lembaga pelatihan.', 'Kepala Lembaga Pelatihan.', '/assets/lspfit/logofit-nobg.png', 0, 1);

INSERT INTO site_settings (setting_key, setting_value) VALUES
  ('about_title', 'Tentang LSP FIT'),
  ('about_description', 'LSP FIT adalah Lembaga Sertifikasi Profesi Fasilitator, Instruktur dan Tenaga Kepelatihan berlisensi BNSP yang menjaga mutu dan relevansi sertifikasi kompetensi.'),
  ('vision', 'Menjadi lembaga sertifikasi profesi yang terpercaya, objektif, dan relevan dengan kebutuhan dunia kerja nasional.'),
  ('mission', 'Menyelenggarakan sertifikasi kompetensi sesuai standar BNSP dan SKKNI.\nMenjaga objektivitas, konsistensi, dan mutu proses asesmen.\nMemperluas akses sertifikasi melalui layanan online dan offline.\nMembangun kemitraan dengan pemerintah, industri, lembaga pelatihan, dan perguruan tinggi.\nMendukung pengakuan kompetensi fasilitator, instruktur, dan tenaga kepelatihan.'),
  ('contact_email', 'info.lspfit@gmail.com'),
  ('contact_website', 'www.sertifikasifit.com'),
  ('contact_phone', '0811-1210-1007'),
  ('contact_address', 'Ruko Akasa Blok B No 5, Jl. Raya Astek, Kp. Jombang, Kel. Lengkong Gudang Timur, Kec. Serpong, Kota Tangerang Selatan'),
  ('home_hero_title', 'LSP FIT untuk kompetensi profesional yang diakui.'),
  ('home_hero_description', 'LSP FIT menyelenggarakan sertifikasi kompetensi bagi fasilitator, instruktur, dan tenaga kepelatihan dengan standar BNSP dan kebutuhan dunia kerja.'),
  ('home_hero_button_text', 'Lihat Skema Sertifikasi'),
  ('home_hero_button_url', '/kegiatan.html'),
  ('home_hero_image', '/assets/lspfit/logofit-nobg.png'),
  ('home_profile_kicker', 'Tentang LSP FIT'),
  ('home_profile_title', 'Lembaga Sertifikasi Profesi berlisensi BNSP'),
  ('home_profile_card_title', 'Berlisensi BNSP'),
  ('home_profile_card_description', 'LSP FIT memiliki lisensi BNSP LSP-444-ID dan melaksanakan sertifikasi mengacu SKKNI No. 333 Tahun 2020.'),
  ('home_members_kicker', 'Struktur LSP FIT'),
  ('home_members_title', 'Tim pengelola sertifikasi profesional'),
  ('home_partners_kicker', 'Mitra & Kerjasama'),
  ('home_partners_title', 'Jaringan kolaborasi LSP FIT'),
  ('home_cta_title', 'Siap mengikuti sertifikasi kompetensi?'),
  ('home_cta_description', 'Hubungi tim LSP FIT untuk mendapatkan informasi skema, persyaratan, jadwal, dan proses pendaftaran.'),
  ('home_cta_button_text', 'Konsultasi Sekarang'),
  ('home_cta_button_url', '/kontak.html'),
  ('home_show_activities', '0'),
  ('home_show_profile', '1'),
  ('home_show_members', '1'),
  ('home_show_partners', '1'),
  ('home_show_cta', '1'),
  ('home_section_order', 'profile,members,partners,cta'),
  ('content_seed_version', '20260925-dynamic-about-media'),
  ('home_partners_layout', 'carousel'),
  ('home_members_layout', 'cards'),
  ('about_profile_kicker', 'Profil'),
  ('about_profile_title', 'Berlisensi BNSP'),
  ('about_profile_description', 'LSP FIT memiliki lisensi BNSP dengan Nomor LSP-444-ID dan berhak melaksanakan uji kompetensi mengacu SKKNI No. 333 Tahun 2020.'),
  ('about_support_kicker', 'Dukungan'),
  ('about_support_title', 'Didukung Asosiasi'),
  ('about_support_description', 'LSP FIT didukung oleh APTISI wilayah 3 DKI Jakarta dan AFIN sebagai asosiasi pendukung dalam pengembangan kompetensi.'),
  ('about_reach_kicker', 'Jangkauan'),
  ('about_reach_title', 'Jangkauan Nasional'),
  ('about_reach_description', 'LSP FIT membangun jaringan dengan instansi pemerintah, lembaga pelatihan, institusi pendidikan, dunia usaha, dan dunia industri di seluruh Indonesia.'),
  ('about_leader_kicker', 'Sambutan Pimpinan'),
  ('about_leader_title', 'Membangun kepercayaan melalui kompetensi'),
  ('about_leader_quote', 'LSP FIT hadir untuk memastikan setiap proses sertifikasi berjalan objektif, profesional, dan memberi nilai nyata bagi peserta, dunia kerja, serta ekosistem pelatihan di Indonesia.'),
  ('about_leader_name', 'Fitri Firmansyah'),
  ('about_leader_role', 'Direktur LSP FIT'),
  ('about_video_kicker', 'Kenali LSP FIT'),
  ('about_video_title', 'Video perkenalan'),
  ('about_video_description', 'Area ini disiapkan untuk menampilkan video profil dan layanan LSP FIT.'),
  ('about_video_url', ''),
  ('about_video_note_label', 'Siap diisi'),
  ('about_video_note_description', 'Gunakan video yang menjelaskan profil lembaga, layanan sertifikasi, skema, dan alur pendaftaran.')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
