-- Menandai konfigurasi konten terbaru LSP FIT.
INSERT INTO site_settings (setting_key, setting_value) VALUES
  ('content_seed_version', '20260924-lsp-fit-content'),
  ('home_partners_layout', 'carousel'),
  ('home_members_layout', 'cards'),
  ('about_title', 'Tentang LSP FIT'),
  ('about_description', 'LSP FIT adalah Lembaga Sertifikasi Profesi Fasilitator, Instruktur dan Tenaga Kepelatihan berlisensi BNSP yang menjaga mutu dan relevansi sertifikasi kompetensi.'),
  ('vision', 'Menjadi lembaga sertifikasi profesi yang terpercaya, objektif, dan relevan dengan kebutuhan dunia kerja nasional.'),
  ('mission', 'Menyelenggarakan sertifikasi kompetensi sesuai standar BNSP dan SKKNI.\nMenjaga objektivitas, konsistensi, dan mutu proses asesmen.\nMemperluas akses sertifikasi melalui layanan online dan offline.\nMembangun kemitraan dengan pemerintah, industri, lembaga pelatihan, dan perguruan tinggi.\nMendukung pengakuan kompetensi fasilitator, instruktur, dan tenaga kepelatihan.'),
  ('contact_email', 'info.lspfit@gmail.com'),
  ('contact_website', 'www.sertifikasifit.com'),
  ('contact_phone', '0811-1210-1007'),
  ('contact_address', 'Ruko Akasa Blok B No 5, Jl. Raya Astek, Kp. Jombang, Kel. Lengkong Gudang Timur, Kec. Serpong, Kota Tangerang Selatan'),
  ('home_hero_title', 'LSP FIT untuk kompetensi profesional yang diakui.'),
  ('home_hero_description', 'LSP FIT menyelenggarakan sertifikasi kompetensi bagi fasilitator, instruktur, dan tenaga kepelatihan dengan standar BNSP dan kebutuhan dunia kerja.'),
  ('home_hero_button_text', 'Lihat Skema Sertifikasi'),
  ('home_hero_button_url', '/kegiatan.html'),
  ('home_hero_image', '/assets/lspfit/logofit-nobg.png'),
  ('home_profile_kicker', 'Tentang LSP FIT'),
  ('home_profile_title', 'Lembaga Sertifikasi Profesi berlisensi BNSP'),
  ('home_profile_card_title', 'Berlisensi BNSP'),
  ('home_profile_card_description', 'LSP FIT memiliki lisensi BNSP LSP-444-ID dan melaksanakan sertifikasi mengacu SKKNI No. 333 Tahun 2020.'),
  ('home_members_kicker', 'Struktur LSP FIT'),
  ('home_members_title', 'Tim pengelola sertifikasi profesional'),
  ('home_partners_kicker', 'Mitra & Kerjasama'),
  ('home_partners_title', 'Jaringan kolaborasi LSP FIT'),
  ('home_cta_title', 'Siap mengikuti sertifikasi kompetensi?'),
  ('home_cta_description', 'Hubungi tim LSP FIT untuk mendapatkan informasi skema, persyaratan, jadwal, dan proses pendaftaran.'),
  ('home_cta_button_text', 'Konsultasi Sekarang'),
  ('home_cta_button_url', '/kontak.html'),
  ('home_show_activities', '0'),
  ('home_show_profile', '1'),
  ('home_show_members', '1'),
  ('home_show_partners', '1'),
  ('home_show_cta', '1'),
  ('home_section_order', 'profile,members,partners,cta'),
  ('about_profile_kicker', 'Profil'),
  ('about_profile_title', 'Berlisensi BNSP'),
  ('about_profile_description', 'LSP FIT memiliki lisensi BNSP dengan Nomor LSP-444-ID dan berhak melaksanakan uji kompetensi mengacu SKKNI No. 333 Tahun 2020.'),
  ('about_support_kicker', 'Dukungan'),
  ('about_support_title', 'Didukung Asosiasi'),
  ('about_support_description', 'LSP FIT didukung oleh APTISI wilayah 3 DKI Jakarta dan AFIN sebagai asosiasi pendukung dalam pengembangan kompetensi.'),
  ('about_reach_kicker', 'Jangkauan'),
  ('about_reach_title', 'Jangkauan Nasional'),
  ('about_reach_description', 'LSP FIT membangun jaringan dengan instansi pemerintah, lembaga pelatihan, institusi pendidikan, dunia usaha, dan dunia industri di seluruh Indonesia.')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
