DELETE FROM kegiatan;
DELETE FROM anggota;

INSERT INTO site_settings (setting_key, setting_value) VALUES
  ('about_title', 'Tentang LSP FIT'),
  ('about_description', 'LSP FIT adalah Lembaga Sertifikasi Profesi Fasilitator, Instruktur dan Tenaga Kepelatihan berlisensi BNSP yang menjaga mutu dan relevansi sertifikasi kompetensi.'),
  ('vision', 'Menjadi lembaga sertifikasi profesi yang terpercaya, objektif, dan relevan dengan kebutuhan dunia kerja nasional.'),
  ('mission', 'Menyelenggarakan sertifikasi kompetensi sesuai standar BNSP dan SKKNI.\nMenjaga objektivitas, konsistensi, dan mutu proses asesmen.\nMemperluas akses sertifikasi melalui layanan online dan offline.\nMembangun kemitraan dengan pemerintah, industri, lembaga pelatihan, dan perguruan tinggi.\nMendukung pengakuan kompetensi fasilitator, instruktur, dan tenaga kepelatihan.'),
  ('contact_email', 'info.lspfit@gmail.com'),
  ('contact_website', 'www.sertifikasifit.com'),
  ('contact_phone', '0811-1210-1007'),
  ('contact_address', 'Ruko Akasa BSD Blok B Nomor 5, Jl. Raya Lengkong Gudang Timur, Tangerang Selatan 15228'),
  ('home_hero_title', 'LSP FIT untuk kompetensi profesional yang diakui.'),
  ('home_hero_description', 'LSP FIT menyelenggarakan sertifikasi kompetensi bagi fasilitator, instruktur, dan tenaga kepelatihan dengan standar BNSP dan kebutuhan dunia kerja.'),
  ('home_hero_button_text', 'Lihat Skema Sertifikasi'),
  ('home_hero_button_url', '/kegiatan.html'),
  ('home_hero_image', '/assets/lspfit/logofit-nobg.png'),
  ('home_activities_kicker', 'LSP FIT dalam angka'),
  ('home_activities_title', 'Pengalaman dan jangkauan nasional'),
  ('home_activities_description', 'Sertifikasi kompetensi yang dikelola secara profesional, terukur, dan mudah diakses.'),
  ('home_profile_kicker', 'Tentang LSP FIT'),
  ('home_profile_title', 'Lembaga Sertifikasi Profesi berlisensi BNSP'),
  ('home_profile_card_title', 'Berlisensi BNSP'),
  ('home_profile_card_description', 'LSP FIT memiliki lisensi BNSP LSP-444-ID dan melaksanakan sertifikasi mengacu SKKNI No. 333 Tahun 2020.'),
  ('home_members_kicker', 'Struktur LSP FIT'),
  ('home_members_title', 'Tim pengelola sertifikasi profesional'),
  ('home_partners_kicker', 'Mitra & Kerjasama'),
  ('home_partners_title', 'Jaringan kolaborasi LSP FIT'),
  ('home_cta_title', 'Siap mengikuti sertifikasi kompetensi?'),
  ('home_cta_description', 'Hubungi tim LSP FIT untuk mendapatkan informasi skema, persyaratan, jadwal, dan proses pendaftaran.'),
  ('home_cta_button_text', 'Konsultasi Sekarang'),
  ('home_cta_button_url', '/kontak.html'),
  ('home_show_activities', '0'),
  ('home_section_order', 'profile,members,partners,cta')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
